In [1]:
import numpy as np

In [3]:
np_2d = np.array([[1.2, 1.4, 1.9, 1.7, 1.6], [37.7, 56.3, 62.8, 49.7, 62.5]])

In [4]:
np_2d

array([[  1.2,   1.4,   1.9,   1.7,   1.6],
       [ 37.7,  56.3,  62.8,  49.7,  62.5]])

In [5]:
np_2d.shape

(2, 5)

In [6]:
n_np_2d = np.array([[1.2, 1.4, 1.9, 1.7, 1.6], [37.7, 56.3, 62.8, 49.7, "62.5"]])
n_np_2d

array([['1.2', '1.4', '1.9', '1.7', '1.6'],
       ['37.7', '56.3', '62.8', '49.7', '62.5']], 
      dtype='<U32')

In [7]:
np_2d[0]

array([ 1.2,  1.4,  1.9,  1.7,  1.6])

In [9]:
np_2d[1][1]

56.299999999999997

In [10]:
np_2d[1, 1]

56.299999999999997

In [18]:
np_2d[:,1:3]

array([[  1.4,   1.9],
       [ 56.3,  62.8]])

In [30]:
np_2d[1,:]

array([ 37.7,  56.3,  62.8,  49.7,  62.5])

In [32]:
x = np.array([[1, 2, 3],
              [1, 2, 3]])
y = np.array([[1, 1, 1],
              [1, 2, 3]])
z = x - y
z

array([[0, 1, 2],
       [0, 0, 0]])