In [1]:
import numpy as np

In [6]:
arr = np.array([1.2, 1.4, 1.9, 1.7, 1.6])
np_2d = np.array([[1.2, 1.4, 1.9, 1.7, 1.6], [37.7, 56.3, 62.8, 49.7, 62.5]])

In [8]:
np.mean(arr)

1.5600000000000001

In [9]:
np.median(arr)

1.6000000000000001

In [15]:
np_2d[0:1:,]

array([[ 1.2,  1.4,  1.9,  1.7,  1.6]])

In [16]:
np.median(np_2d[0:1:,])

1.6000000000000001

In [19]:
np.corrcoef(np_2d[:,0], np_2d[:,1])

array([[ 1.,  1.],
       [ 1.,  1.]])

In [20]:
np.std(arr)

0.24166091947189142

# Create list

In [23]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np_city

array([[  1.72,  98.22],
       [  1.39,  51.91],
       [  1.83,  65.09],
       ..., 
       [  1.48,  70.71],
       [  1.64,  65.51],
       [  1.5 ,  37.56]])

In [34]:
np_city[:,0]

array([ 1.72,  1.39,  1.83, ...,  1.48,  1.64,  1.5 ])

In [37]:
np_city[1:,]

array([[  1.39,  51.91],
       [  1.83,  65.09],
       [  1.83,  57.21],
       ..., 
       [  1.48,  70.71],
       [  1.64,  65.51],
       [  1.5 ,  37.56]])

In [38]:
np_city[1:3:,]

array([[  1.39,  51.91],
       [  1.83,  65.09]])

In [40]:
np_city[1:3:,0]

array([ 1.39,  1.83])

In [35]:
np.mean(np_city[:,0])

1.7450080000000001

In [44]:
np.median(np_city[:,0])

1.75

In [47]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[ 1.        ,  0.01007206],
       [ 0.01007206,  1.        ]])

In [48]:
np.sum(np_city[:,0])

8725.0400000000009

In [56]:
np.sort(np_city[:,0])

array([ 0.94,  1.05,  1.13, ...,  2.38,  2.39,  2.39])

In [50]:
np.sort?