In [31]:
import numpy as np
from numpy import pi

In [7]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a

array([20, 30, 40, 50])

In [8]:
b

array([0, 1, 2, 3])

In [6]:
c = a-b
c

array([20, 29, 38, 47])

In [9]:
b**2

array([0, 1, 4, 9])

In [12]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [13]:
10*c

array([200, 290, 380, 470])

In [15]:
a<35

array([ True,  True, False, False], dtype=bool)

## Elementwise product

In [16]:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
             [3,4]] )
A*B 

array([[2, 0],
       [0, 4]])

## Matrix product

In [17]:
A.dot(B)

array([[5, 4],
       [3, 4]])

## Another matrix product

In [18]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [20]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [24]:
b

array([[ 6.96176389,  6.15431585,  6.64806932],
       [ 6.58159376,  6.53335857,  6.0749873 ]])

In [23]:
b += a
b

array([[ 6.96176389,  6.15431585,  6.64806932],
       [ 6.58159376,  6.53335857,  6.0749873 ]])

In [33]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [34]:
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [35]:
c.dtype.name

'float64'

In [39]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [40]:
d.dtype.name

'complex128'

## unary operations

In [41]:
a = np.random.random((2,3))
a

array([[ 0.25043718,  0.22943833,  0.10952575],
       [ 0.58983798,  0.25721836,  0.67223833]])

In [42]:
a.sum()

2.1086959391357141

In [43]:
a.min()

0.10952575367126882

In [44]:
a.max()

0.67223833106793429

## Changing axis of uniry operations

In [45]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [51]:
b.sum(axis=1) 

array([ 6, 22, 38])

In [52]:
b.min(axis=1) 

array([0, 4, 8])

### Cumulative sum along each row

In [53]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal Functions

In [54]:
B = np.arange(3)
B

array([0, 1, 2])

In [55]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [56]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [57]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([ 2.,  0.,  6.])