In [16]:
import numpy as np

In [17]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [18]:
a[2]

8

In [19]:
a[2:5]

array([ 8, 27, 64])

In [20]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [21]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [24]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/home/mamun/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [25]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [26]:
b[2,3]

23

In [31]:
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [32]:
# each row in the second column of b
b[0:3, 2] 

array([ 2, 12, 22])

In [33]:
b[ : ,1] 

array([ 1, 11, 21, 31, 41])

In [34]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [35]:
b[-1]

array([40, 41, 42, 43])

In [36]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

In [37]:
c.shape

(2, 2, 3)

In [43]:
c[1,...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [42]:
c[...,2] # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [44]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [45]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
