In [16]:
import numpy as np

In [17]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 9.,  9.,  6.,  5.],
       [ 5.,  5.,  3.,  5.],
       [ 3.,  0.,  1.,  2.]])

In [18]:
a.shape

(3, 4)

In [19]:
a.ravel()  # returns the array, flattened

array([ 9.,  9.,  6.,  5.,  5.,  5.,  3.,  5.,  3.,  0.,  1.,  2.])

## Reshape a Array

In [20]:
a.reshape(6,2)

array([[ 9.,  9.],
       [ 6.,  5.],
       [ 5.,  5.],
       [ 3.,  5.],
       [ 3.,  0.],
       [ 1.,  2.]])

## Transpos of a array / matrix

In [21]:
a.T  # returns the array, transposed

array([[ 9.,  5.,  3.],
       [ 9.,  5.,  0.],
       [ 6.,  3.,  1.],
       [ 5.,  5.,  2.]])

In [22]:
a.T.shape

(4, 3)

In [24]:
a.shape

(3, 4)

In [25]:
a

array([[ 9.,  9.,  6.,  5.],
       [ 5.,  5.,  3.,  5.],
       [ 3.,  0.,  1.,  2.]])

In [26]:
a.resize((2,6))
a

array([[ 9.,  9.,  6.,  5.,  5.,  5.],
       [ 3.,  5.,  3.,  0.,  1.,  2.]])

## Use -1 to calculate other dimension autometicaly

In [27]:
a.reshape(3,-1)
a

array([[ 9.,  9.,  6.,  5.,  5.,  5.],
       [ 3.,  5.,  3.,  0.,  1.,  2.]])